{
 "title": "Seesaw Metrics",
 "panels": [
  {
   "title": "Active Items",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "seesaw_active_items", "legendFormat": "{{project}}" }
   ]
  },
  {
   "title": "Item States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "seesaw_items_state{state=\"running\"}",
     "legendFormat": "running"
    },
    {
     "expr": "seesaw_items_state{state=\"completed\"}",
     "legendFormat": "completed"
    },
    {
     "expr": "seesaw_items_state{state=\"failed\"}",
     "legendFormat": "failed"
    },
    {
     "expr": "seesaw_items_state{state=\"canceled\"}",
     "legendFormat": "canceled"
    }
   ]
  },
  {
   "title": "Bandwidth In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "seesaw_bandwidth_receiving_bytes_per_second",
     "legendFormat": "receiving"
    },
    {
     "expr": "seesaw_bandwidth_sending_bytes_per_second",
     "legendFormat": "sending"
    }
   ]
  }
 ]
}